spring.application.name=parser
server.port=8000

# Oracle DB connection
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.datasource.url=jdbc:oracle:thin:@db1_high?TNS_ADMIN=D:/Oracle_Cloud/Wallet_db1
spring.datasource.username=ADMIN
spring.datasource.password=Albert@ein32


spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update